### ISSUE TITLE
Notepad++ Not Going to Result Line

### ISSUE THREAD

**Issue by sco-owe** [Arjailer/Bugs#21]
## Describe the bug

Notepad++ not going to result line

## Reproduction steps

Steps to reproduce the behaviour:
- Do a search
- In the results select a matching line in a file
- Right click and select open in Notepad++
- Notepad++ opens and shows the file but doesn't go to the line (in previous versions it did)

## Expected behaviour

Notepad++ opens, shows the file **and** goes to the selected line

## Version information (please complete the following information):
 - 1.20
 - Windows 10

**Comment by Arjailer** [comment]
Fixed in v1.21

Problem was caused by the way Grind finds pre-defined text editors and matches them to the system default text editor.

It was "finding" the 64-bit version of Notepad++, but the user had the 32-bit version installed. It would then fail to find the 64-bit executable, but it wouldn't keep looking through the pre-defined editors and would instead fall back to passing just the filename, but not the line+column numbers.

It now keeps looking (and finds the 32-bit version) if the executable isn't found.

I also loosened the name matching (so it'll match anything beginning with ```Notepad++``` instead of looking for an exact match to ```Notepad++ : a free (GNU) source code editor```) - that turned out not to be the problem, but it seemed like a worthwhile (and potentially futureproof) change so I left it in.

Also added logging of the system default text editor in case we ever need to debug this again - search ```log.txt``` for ```system text file association```
